// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhxdocynplmkefpehejh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoeGRvY3lucGxta2VmcGVoZWpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNjM2NTQsImV4cCI6MjA2MjczOTY1NH0.Ra9vzVgkgODPP2-6hC2o0Q-14urfdJ4VQECt1IRGtW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);